### ISSUE TITLE
Multiple Problems

### ISSUE THREAD

**Issue by Phracea** [A5H73Y/Parkour#100]
First- How do you disable achieving all checkpoints before finishing?
Second - How do I change what blocks do what in the config cause on the older version I was using it let me but now I don't see it.
Third - The plugin sets all course names to lower case letters which bothers me even after trying to change them back in the courses.yml.

**Comment by Phracea** [comment]
Another problem I just came across - I pasted in my old courses.yml into the new courses.yml and now it says none of the courses exist

**Comment by steve4744** [comment]
I can help you with the first point. In config.yml put:
OnFinish:
  EnforceCompletion: false

**Comment by A5H73Y** [comment]
Third - This is to have the case no longer matter, in Parkour < 4.0 a course could be called "level1" and "Level1" which was annoying as it wouldn't recognise it if it was the wrong case.
To combat this I allowed the plugin to display it in whichever case you would like for example a join sign could display it as "LEVEL1" and it would still resolve to "level1".
Forth - So the plugin automates upgrading from a previous version by converting the data to a format it understands, you will need to allow the plugin to do it for you, or do it all manually which could take significantly longer.
I hope this helps.

**Comment by A5H73Y** [comment]
A week with no response, and no actual bug to raise, going to close this ticket.
