### ISSUE TITLE
Possible Suggestions for features.

### ISSUE THREAD

**Issue by eXish** [A5H73Y/Parkour#101]
So this plugin is just plain awesome, it has much more than any other kind I've seen before. However there are two major issues that I've found that seem to be messing with some maps I've set up on my server. These issues only affect me and don't necessarily need to be added but they would make game-play for players much better and allow creators to make much crazier maps.

Firstly, one map I've set up before using this plugin had teleportation as a big part of it. But when pressure plates are stepped on after joining a map they do nothing, like they were never stepped on. This could be fixed in general, but if not then I would suggest a teleportation special block. I don't know how this would be implemented, but it would definitely be a cool addition!
Secondly, all of the maps could benefit from this addition, especially players. Adding a starting pressure plate that actually starts a map's timer. This would be nice since right now the plugin never notifies the player when the time starts (So I'm assuming it starts right when a player joins). It would allow players to prepare before starting, and they can decide to leave before they start it if they decide against playing a map after looking at it.

I hope you will take these suggestions into consideration and thanks so much for your time!

**Comment by A5H73Y** [comment]
Hi eXish, thank you for the feedback!
Luckily your first problem is a simple config change, find "OnCourse.PreventPlateStick" and set this to **false** then enter "/pa reload". The purpose of this option is for popular courses, if one player was stood on the pressure plate, others would not be able to activate it / the checkpoint.
That is interesting and the implementation would need to be considered, the performance hit every time you walk on a pressure plate as it would have to search every single course to see if it is the beginning of any of them, I could create it and disable it by default.
Would the player have to "join" the course first, and then walk on the plate to start it?
Or could you have 10 courses next to each other and you can walk on the pressure plate of which one you want to start?

**Comment by A5H73Y** [comment]
For now I've added an option "OnJoin.TreatFirstCheckpointAsStart", which simply resets your time once you step on the first checkpoint. It's a cheap fix but hopefully it works for what you need?
Let me know if you'd like me to try anything else.

**Comment by eXish** [comment]
So I haven't tried out this feature yet, but it's what I was thinking to fix the problem. I was thinking it should be more like you officially start a course on touching the first pressure plate/checkpoint. So basically the option like you said where you could have 10 maps lined up and players could choose. It's more like the join sign should be for warping to a map instead of starting it in my opinion, so maybe the /pa setstart is actually the warp in command and then the first checkpoint starts it (at least that's what I envision). Also thanks for telling me about the first solution, had no idea that was in the config.

**Comment by steve4744** [comment]
9de47d3  causes **all** pressure plates before the first checkpoint to reset the timer.

**Comment by A5H73Y** [comment]
Achieved with treating first checkpoint as start, and auto starts in Parkour v5.0.
Closing
