### ISSUE TITLE
"/parkour" not registered as parkour commands

### ISSUE THREAD

**Issue by mallamace** [A5H73Y/Parkour#102]
I apologize in advance if this is more of a support question than an actual issue, however I've done my research and I have not found a solution.

Issue: I have installed Parkour typing "/parkour" or "/pa setlobby" does not work.

System:
Plugins installed - WorldEdit, PermissionsEx,  Vault, Multiverse-Core, Bedwars, Essentials, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, Parkour, EssentialsSpawn, EssentialsXMPP
Spigot 1.12.2 @ Java 8

**Comment by A5H73Y** [comment]
Hi, can you please check your startup logs to see if Parkour properly started?
Does it error when you enter those commands, or does it say not recognized? 
If you would prefer more personal and faster responses, consider joining the Discord support server.

**Comment by mallamace** [comment]
Hi A5H73Y, thanks for  making such a great plugin. After your message, I checked again and it started working, I did not make any changes, I think it might have been an issue with the server.
