### ISSUE TITLE
Internal Error when attempting to join a parkour in 1.13

### ISSUE THREAD

**Issue by Christoffer113** [A5H73Y/Parkour#104]
When trying to join a parkour (Newly made, I dont have a previously made one to test with although I have used the plugin before and it has worked) I get an internal error message. It also fails when using a sign with no error message. No errors appear in the server command prompt.

**Comment by A5H73Y** [comment]
Hi, Parkour doesn't officially support 1.13 just yet, but it will be coming eventually.
For now there will be one more release as v4.8 with a few nice features and fixes, then I will be creating Parkour v5.0 which will be to support 1.13 and I hope to support all the currently supported older versions.
If you want to join the Discord server, I post announcements on progress on there.

**Comment by A5H73Y** [comment]
I'm closing this ticket as support for 1.13 has now been introduced and no problems should arise when joining the server now.
