### ISSUE TITLE
missing command to set the finishing block?

### ISSUE THREAD

**Issue by smmmadden** [A5H73Y/Parkour#116]
I went through the tutorial for the first time using Parkour and it was very well done, except there is one important piece missing.
NOTE: You will need to place a Finish Block manually for the player to be able to finish.

There is no command for /pa setfinish or anything resembling marking that block as the finish and get rewarded.  So when I go through it, I see the message I did all checkpoints.  But I don't get rewarded.
![image](https://user-images.githubusercontent.com/10309346/45931336-df4a5880-bf3a-11e8-8d19-9a309f38d984.png)

**PaperSpigot** 1.13.1 (Build 279)
**Parkour** 4.8
**PlaceholderAPI** 2.9.2
**BountifulAPI** 1.6.4

Also using latest versions of the following plugins: 
[14:23:35 INFO]: Plugins (57): Arconix*, AutoBroadcasterPlus*, AutoTorch, BountifulAPI, BungeeServerSigns*, BungeeTabListPlus*, ColorCodes*, CommandSync*, CorpseReborn*, CreativeGates*, CreeperHeal*, DeluxeJoin, DeluxeMenus*, dynmap*, EditableSign*, EnchantableBlocks, Essentials*, EssentialsAntiBuild*, EssentialsChat*, EssentialsExtras*, EssentialsGeoIP*, EssentialsProtect*, EssentialsSpawn*, HeadDatabase*, HorseTpWithMe, Jobs, Kotlin4MC*, Links*, LuckPerms*, LWC, MassiveBooks*, MassiveCore*, Missing_Recipes, OpenInv*, PacketListenerApi*, Parkour*, PlaceholderAPI, ProtocolLib*, PulseHealth*, Quests*, QuickShop, Realistic-Swimming, Residence, Ridables, SaneEconomy*, Seashells, SecurityVillagers, SelectionVisualizer, Sockets4MC*, TintHealth*, TreeAssist, Vault*, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldSystem

**Comment by A5H73Y** [comment]
So "/pa setfinish" is marking the status of the course, in that it's "finished" i.e. ready for players to join.
A Finish Block is part of the ParkourKit, and thus can be different for each course so it would not make sense for the plugin to do this part for you, meaning you must place it yourself with your own choice of Finish Block.
As far as I'm aware this is working as intended, if you can make suggestions to make it more clear that could be beneficial. I hope that makes sense.

**Comment by smmmadden** [comment]
ah now that makes sense.  I think then what you need in the tutorial is to elaborate more on that step (since it wasn't clear leading up to it step by step) you have it in.  Something about continue in Part 4 by placing one of the Parkour Kit Blocks as your finish block and then /pa finish course

I went back to the test course I created and used /pa kit default and my inventory cleared out and couldn't find any command to get rid of the kit and return my inventory.  Leaving the world and returning brings me back to my spawn point (as I want), but all my inventory is gone.

If it helps, I was following the tutorial as a step-by-step flow since I have no reference point being new to this.  It's a bit awkward too trying to figure out what command list to return (e.g. /pa cmnds, /pa cmnds 1 thru 4) but I guess I'll get used to it.  I'm just used to typing in one command to see all of them up front. :-)

**Comment by smmmadden** [comment]
That's very clear now in the edited steps for the finish blocks.  Thank you!

Wow, I'm surprised no one has mentioned about losing their inventory.  Couldn't we read their current inventory and save it in memory or a tempfile when interacting with each of the kit commands and when the user does /pa kit done or something like that it would remove the kit blocks and restore the previous inventory?  I've seen similar behavior with other plugins that interact with a users inventory system.  

I guess that makes sense, it's kind of like worldedit or essentials where there are a ton of commands.  One thing I did try is on the server console to use /pa cmds, /pa cmnds all and /pa cmnds 0 hoping that at least I'd see the full listing there since paging doesn't matter nor does the grouping necessarily matter.  What do you think?

Thanks - Steve
