### ISSUE TITLE
Scoreboard improvements

### ISSUE THREAD

**Issue by A5H73Y** [A5H73Y/Parkour#121]
The text for each entry should be configurable, through the strings.yml file.
Note that each server version will have a different maximum length before it errors, so this must be checked and truncated to avoid displaying errors to the user.
A display sequence number could be attached to each entry, to allow the user to specify the order of the results, using a comparator.

**Comment by steve4744** [comment]
Should this be "scoreboard" improvements not "leaderboard"?

**Comment by A5H73Y** [comment]
Customisable text headings and better code, will truncate anything over 16 chars if on version < 1.13 to prevent errors.
