### ISSUE TITLE
On-Join Message to Player Removal or Editing

### ISSUE THREAD

**Issue by AllispossibleTechSMC** [A5H73Y/Parkour#126]
I would like to remove or change/edit the message that the plugin sends to every player when they join the server.   The message looks like something like this:

[Parkour] This server uses Parkour 5.1 (Version)

**Comment by A5H73Y** [comment]
To remove it, open config.yml and find "Other.Display.JoinWelcomeMessage" and set this to **false**.
To edit it, open strings.yml and find "Event.Join" and set this to whatever value you want.
Both will require you to enter **/pa reload** after making your changes.

**Comment by AllispossibleTechSMC** [comment]
> To remove it, open config.yml and find "Other.Display.JoinWelcomeMessage" and set this to **false**.
> To edit it, open strings.yml and find "Event.Join" and set this to whatever value you want.
> Both will require you to enter **/pa reload** after making your changes.

Thank you really much!
