### ISSUE TITLE
Stuck in middle of fance!!

### ISSUE THREAD

**Issue by whiteblack2** [A5H73Y/Parkour#128]
I stuck in middle of fance in jungle!!

**Comment by whiteblack2** [comment]
i get wedged in middle of fance in jungle

**Comment by A5H73Y** [comment]
Hi @whiteblack2, I'm afraid I don't know how to help you or how this is relevant to this Project.
I'll give the benefit of the doubt and assume you're stuck while on a course, you can use the tools in the hotbar while on a course to either leave or go back to the last checkpoint.

**Comment by whiteblack2** [comment]
But I don't  know how to back to the last checkpoint

**Comment by A5H73Y** [comment]
@whiteblack2 Has this been resolved and can I close the ticket?
