### ISSUE TITLE
Players collide with each other on 1.12.2 Paper while in parkour maps

### ISSUE THREAD

**Issue by RealmportalMC** [A5H73Y/Parkour#130]
https://timings.aikar.co/?id=307bf534ef3b45dfb66aea57f38c7718

Information about my server.

I have played around with player collisions before in paper.yml and it has been an issue for ages

**Comment by steve4744** [comment]
As a workaround, to avoid being pushed off a block/course, you can toggle the other players invisible (using the Parkour hotbar item). If they are invisible, then they can't push you.

**Comment by A5H73Y** [comment]
Am I right to think this was fixed by removing the Scoreboard by default @steve4744?
