### ISSUE TITLE
Location prior to join treated as Lobby

### ISSUE THREAD

**Issue by A5H73Y** [A5H73Y/Parkour#144]
When configured, when the player leaves / finishes a course they should be teleported back to where they were before they joined the course.

If this is enabled, their location will be saved to their PlayerInfo and loaded and teleported to when they leave / finish the course.

**Comment by A5H73Y** [comment]
Can this be closed now, @steve4744 ?

**Comment by steve4744** [comment]
@A5H73Y yes this can be closed.
