### ISSUE TITLE
Liquid detection is too aggressive

### ISSUE THREAD

**Issue by URoulon** [A5H73Y/Parkour#147]
The title says it all.

On my server, players die when hitting water or lava but some jumps are near impossible now.
For example, it is now impossible to jump on a lilypad in the middle of a lake because you'll get killed when landing. Jumping next to water is impossible, being on a block and sneaking above water kills you now.

**Comment by steve4744** [comment]
Instead of setting water as a death block, set DieInLiquid to true in the _config.yml_.
```
OnCourse:
    DieInLiquid: true
```

**Comment by URoulon** [comment]
After some testing, it turns out that it's the ParkourKit death block check that's causing the issue.
It works just fine when using DieInLiquid.

But we were looking forward to turning off DieInLiquid (and to move that to ParkourKits) to create aquatic parkours to use the newest swimming mechanics...

**Comment by steve4744** [comment]
Yeah, it was just meant as a workaround for now. We've already tested a fix for this. It should be downloadable from the Releases tab some time soon.

**Comment by A5H73Y** [comment]
@steve4744 Fixed this issue and is in the latest (v5.3) release.
