### ISSUE TITLE
Fastest time + rewards

### ISSUE THREAD

**Issue by LogGits** [A5H73Y/Parkour#151]
Is there a way to print out to chat when a player beats a record (gets the fastest time) on a course and give a special reward for breaking records?

Also is there a way to do a first, second and third rewards (all different)?

I am trying to give seperate rewards for first, second, third, and breaking a record, however i am unsure as to how to do this.

**Comment by steve4744** [comment]
You can display new course records by setting this in the config:
```
OnFinish:
  DisplayNewRecords: true
```

**Comment by LogGits** [comment]
Is it possible to only display first time + fastest time?

**Comment by steve4744** [comment]
It currently displays if a player beats the course record, and also if the player beats their own record.
Really it should also display a new record the first time a course  is completed and also the first time a player completes a course.

**Comment by A5H73Y** [comment]
The plugin allows you to specify a command / message for the "course record" as found here: https://a5h73y.github.io/Parkour/#/tutorials/configuring-course?id=parkour-events
There are plans to improve this system to be more details which will be covered in #262.
