### ISSUE TITLE
Actionbar time

### ISSUE THREAD

**Issue by LogGits** [A5H73Y/Parkour#152]
Can you add a way to put the course/time in the actionbar. Something like 
`{course_name} | {checkpoints}/{totalCheckpoints} | {time}`

**Comment by A5H73Y** [comment]
I feel this is missing the point of the action bar functionality, it would appear clustered and too distracting with it's position so central in the screen.
This is kinda why the scoreboard was created so it can display all this information without taking up too much room / attention. 
What I will take from this ticket is the ability to add the {checkpoints}/{totalCheckpoints} mentioned and add it to the scoreboard.

**Comment by A5H73Y** [comment]
Completed as part of #168.
