### ISSUE TITLE
AsCmd

### ISSUE THREAD

**Issue by Ironman1M** [A5H73Y/Parkour#153]
I can´t use AsCmd with it. I did /ascmd addcmd player pa join auth 

It won´t worked. Other commands worked but pa join don´t worked.

**Comment by Ironman1M** [comment]
When i do it normally throught chat it works but that doesn´t fixes my problem

**Comment by A5H73Y** [comment]
I'm not sure why that doesn't work, if it executes the command as a player I can't see why it wouldn't work.
This could now be achieved by doing "/ascmd addcmd console pac join auth %player%" in Parkour 6.0.
