### ISSUE TITLE
Expansion-Parkour_0nf7pzC.jar update?

### ISSUE THREAD

**Issue by SlimeDog** [A5H73Y/Parkour#160]
Spigot 1.13.2 final or 1.14.4 latest
Parkour 5.3

**Expansion-Parkour_0nf7pzC.jar** is the currently available PAPI expansion for Parkour. But PAPI list command claims that an update is available. Please advise.

**Comment by steve4744** [comment]
Expansion-Parkour_0nf7pzC.jar is the latest, and probably final, version (version 1.4) of the expansion.
As of Parkour 5.3 the expansions have been migrated into the Parkour plugin itself.
If you have 
```
Other:
  PlaceholderAPI:
    Enabled: true
```
in Parkour's config.yml then the expansion is effectively redundant and can be removed from the PAPI expansions folder. It's possible PAPI is seeing the 2 different version numbers as an update being available.

**Comment by SlimeDog** [comment]
Thanks. That was the issue.
