### ISSUE TITLE
Execute command on leave & finish.

### ISSUE THREAD

**Issue by A5H73Y** [A5H73Y/Parkour#167]
When the player leaves a parkour course, a command can be executed regardless of anything. This will allow for triggers of external plugins that don't use the Parkour API.

For example, to re-enable a custom scoreboard via "/(plugin) show" when the player is finished with Parkour, regardless if they failed, completed or quit a course.

**Comment by steve4744** [comment]
Similar to #157

**Comment by A5H73Y** [comment]
There are now 6 parkour events that could trigger a configurable list of commands. 

- Join
- Leave
- Prize 
- Checkpoint
- Death
- Finish (Only triggered when "rewardonce" has been enabled and the player has finished the course again.

Each of these can be added to using the "/pa setcourse (course)" conversation, or a single command using "/pa setcourse (course) command (type) (command)". The %PLAYER% placeholder can be used to insert the player's name into the command before execution.
