### ISSUE TITLE
Current Time not appearing in Scoreboard

### ISSUE THREAD

**Issue by HowAmIFirst** [A5H73Y/Parkour#177]
even though current time is enabled, it does not appear in the scoreboard. running on Spigot 1.8.8

**Comment by steve4744** [comment]
It should work on 1.8.8. Make sure you have
```
OnCourse:
   DisplayLiveTime: true
``` 
as well as the scoreboard settings.

**Comment by A5H73Y** [comment]
I believe this is a non-issue as this has fixed the problem countless times. Closing.
