### ISSUE TITLE
ability to set 1 player allowed on the course at a time

### ISSUE THREAD

**Issue by CaszGamerMD** [A5H73Y/Parkour#188]
i have some great parkour/ course like ideas but the main issue is i want it to be 1 player at a time.

**Comment by Kryniowesegryderiusz** [comment]
Im also waiting for this feature. I'd love to see that <3

**Comment by A5H73Y** [comment]
This has been achieved by Steve, using the command "/pa setplayerlimit (player) (number)", also available as a console command.
