### ISSUE TITLE
Multiple Death Materials including water

### ISSUE THREAD

**Issue by BiGUNMAN** [A5H73Y/Parkour#19]
Hi, it would be much appreciated to see multiple death materials and water being added to the plugin, as many parkour maps people create go through vastly different terrains, and locking the death block to 1 material is somewhat of a map breaker.

**Comment by A5H73Y** [comment]
Hello, this was a decision made when creating Parkour 4.0. Performance was the main area of focus, and having multiple death blocks would take quite a hit when on a course. To combat this I added a potential different deathblock to each course, in the form of ParkourBlocks, as well as this I added an option in the config.yml "OnCourse.DieInLiquid", which will activate a death when the player enters Water or Lava.
I hope this helps.
