### ISSUE TITLE
Preprocess cmd error

### ISSUE THREAD

**Issue by Sylensky** [A5H73Y/Parkour#192]
Hi,
i recently tried out your plugin and it works quite well on 1.15.1. Apparently i still get some annoying errors in the console. It doesn't affect the plugin behaviour since i didn't notice something but here is is one out of the errors:
[PreprocessCmd_err.txt](https://github.com/A5H73Y/Parkour/files/4547166/PreprocessCmd_err.txt)

**Comment by steve4744** [comment]
I  tried to recreate this on the latest version of Paper (paper-229) and had no errors. Your version of paper is quite outdated (paper-62). Can you upgrade to the latest release to see if that fixes the errors?

**Comment by Sylensky** [comment]
sorry for my late reply. I wasn't able to upgrade earlier. 
So the error stayed the same like this image below. 
![image](https://user-images.githubusercontent.com/57076968/81847914-96eb0e80-9554-11ea-80c1-b40ec71ae717.png)
I downloaded then Parkour 5.2 and everything worked fine. So maybe something changed there that wasnt quite benifiting.

**Comment by A5H73Y** [comment]
Reviewing this ticket with 6.0 codebase it doesn't appear as if anything can throw a NPE.
@Sylensky Are you able to join the support server to see if this still occurs with 6.0?
