### ISSUE TITLE
Placeholder Error

### ISSUE THREAD

**Issue by ItsMeGriff** [A5H73Y/Parkour#193]
Don't know if this has been reported but when using %parkour_current_personal_best% it shows the Prefix from the strings config and displays in front of it. So when on a scoreboard it gets very long like Parkour > No time recorded. 

Version: 6.0 latest build 

Thanks :)

**Comment by steve4744** [comment]
Confirmed bug in 6.0. 
Thanks for reporting it.

**Comment by A5H73Y** [comment]
Fixed by Steve in previous commit.
