### ISSUE TITLE
pressure plates not working

### ISSUE THREAD

**Issue by steve4744** [A5H73Y/Parkour#2]
Hi,
Regarding version 4.0 [23/090/2016] on MC1.10.
I have some iron doors operated by pressure plates  (which are not checkpoints) in the course which no longer work. The checkpoint pressure plates work as expected.
Also is there a way to put more than one death block in the config.yml? 
Thanks.

**Comment by A5H73Y** [comment]
Hi Steve, 
Thanks again for reporting issues. It helps the plugin development a lot :)
I have added an option to disable this "OnCourse.PreventPlateStick", this will only affect people that are actually on a course though. I will close this ticket when I release the next build.
Parkour 4.0 has changed the way it uses blocks now, which are in the form of ParkourBlocks for performance reasons. Each set of ParkourBlocks will have it own individual set of blocks (DeathBlock etc.) so the short answer is no, but each course can theoretically have it's own deathblock, hope this helps.
Thanks
