### ISSUE TITLE
Possibility of limiting course reward to once a day.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#20]
Would it be possible to set a limit for how many times someone is able to complete a course that day and receive rewards for it? So you can have an in-game economy payout but limit it to once a day to prevent abuse.

**Comment by A5H73Y** [comment]
This could be a possibility for the future, I will plan on improving how customisable the prizes are given.
Thank you for all of these ideas, I appreciate it @mibby

**Comment by mibby** [comment]
In addition to being able to limit how often one can be rewarded, it would be nice to be able to limit how often someone can attempt a course or re-join after completion. i.e. you have 1 life to try and win a course or you can only place that course once every 24 hours.
