### ISSUE TITLE
BUG: Leaderboard not working

### ISSUE THREAD

**Issue by ProvokedEel** [A5H73Y/Parkour#201]
Hi, the leaderboards are only showing certain players top times, but not everyone on the server. I'm not sure if I'm doing anything wrong...?

Thanks.

**Comment by A5H73Y** [comment]
That doesn't sound quite right. If you only want one top time per-player then this can be configured in the config.yml by setting "OnFinish.UpdatePlayerDatabaseTime" to **true**.
This will only take effect when their best time is beaten so I would advise to reset the leaderboards, enter "/pa recreate", then see if it works as expected.

**Comment by A5H73Y** [comment]
Confirmed solved on Discord.
