### ISSUE TITLE
Additional reward on first course completion

### ISSUE THREAD

**Issue by ZonK256** [A5H73Y/Parkour#202]
I'm looking for an option to give players extra rewards when they complete a course for the first time. There's only "/pa rewardonce" command, but afaik it wouldn't help me with my problem.

**Comment by A5H73Y** [comment]
Hi, I could update it so the course's unique prize could be given after their first completion, then any subsequent completion will give the player the default prize which is configured in the config.yml?

**Comment by ZonK256** [comment]
Well, it's some solution and surely better than nothing, but it would be great to be able to set custom prizes both for first and subsequent completions per course (in my scenario some courses are significantly easier than others and I wouldn't want to discourage players from speedrunning the harder ones).

**Comment by ZonK256** [comment]
I've just noticed that the #157 asks for the same feature, so I guess there's no point in keeping this issue open.
