### ISSUE TITLE
Leaderboard Bug

### ISSUE THREAD

**Issue by DragonLady94** [A5H73Y/Parkour#204]
We have had someone set this up for us and we are now testing it to find that the leaderboard does not work, I have followed the previous person thread changing the setting On finish.UpdatePlayerDatabaseTime: true
but our scoreboard is still not registering.
I will attach a copy of our config over as to what the person had originally sent, hope you can help :)
[Parkour Config.txt](https://github.com/A5H73Y/Parkour/files/4836031/Parkour.Config.txt)

**Comment by steve4744** [comment]
> We have had someone set this up for us and we are now testing it to find that the **leaderboard does not work**, I have followed the previous person thread changing the setting On finish.UpdatePlayerDatabaseTime: true
but our **scoreboard is still not registering**.

Hi, is it the scoreboard or leaderboard as they are different things?
In your config you have
`Scoreboard:
    Enabled: false`
which will be why the scoreboard is not showing.

**Comment by DragonLady94** [comment]
many thanks, changed that and I'm able to see it with a command

**Comment by DragonLady94** [comment]
Hey I was wondering if there was any way to turn the leaderboard into a hologram we are currently using Holographic displays plugin

**Comment by steve4744** [comment]
There is an example of how to do it here: https://www.spigotmc.org/resources/parkour-expansion.41874/

You **don't** need to download the actual parkour expansion pack as its now built into Parkour itself, but the **_example_**half way down the page, just below the list of placeholders, explains how to do it.

If you have any issues with it, please discuss on discord:  https://discord.gg/aENfFKK

**Comment by A5H73Y** [comment]
Closing this issue as Steve has addressed all questions.
