### ISSUE TITLE
Restrict certain courses to challenge mode.

### ISSUE THREAD

**Issue by A5H73Y** [A5H73Y/Parkour#208]
Allow a whitelist of courses to be made "challenge-able".

I'm thinking of a flag system, like "/pa set (course) challenge false" or something similar. Need to think of more options to make "flaggable".

**Comment by ZonK256** [comment]
> Need to think of more options to make "flaggable".

I can think of "fall-able (?)" flag, so that specific course wouldn't be affected by "MaxFallTicks:" option in config.

**Comment by A5H73Y** [comment]
A new "Challenge Only" flag has been added to Courses. When set to true, a Course is only joinable when the Player is in a Challenge. 
The setting can be toggled using the command "/pa challengeonly (course)" or using the Course Settings GUI.
