### ISSUE TITLE
Possibility of direct vault economy course rewarding.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#21]
If vault is enabled, would it be possible to have an economy payout as a prize type? Currently limited to material, command, and xp.

**Comment by A5H73Y** [comment]
Please find the "/pa economy" command, this allows you to set a fee for joining a course, as well as a prize amount for completing a course. You're right in that this isn't documented, so I will consider adding as a prize option.

**Comment by mibby** [comment]
That works, thanks!
