### ISSUE TITLE
Configuring a course

### ISSUE THREAD

**Issue by mcthebest** [A5H73Y/Parkour#211]
My builders made parkour and in order to complete it you need speed 1 can you please add a feature to where when you start the parkour you can have speed 1 or jump boost 2. 
Thank you

**Comment by A5H73Y** [comment]
This has been achieved in the form of the new ParkourMode "Potion", when having the ParkourMode conversation via "/pa setmode (course)" the "potion" option will allow the user to enter a PotionEffect name, followed by an optional duration and amplifier, then an optional join message.
