### ISSUE TITLE
Players get "shaken" because of damage despite DisablePlayerDamage: true

### ISSUE THREAD

**Issue by URoulon** [A5H73Y/Parkour#214]
Basically, when players fall from a height that would've caused that fall damage, they get shaken when they shouldn't.
No actual damage is taken, it's just the shake.

I tested with both Paper and Spigot 1.14.4, same result on both.

I feel like this behaviour was altered at some point, as I remember it not happening before.

**Comment by A5H73Y** [comment]
I believe this has been fixed in 6.0 as the EntityDamageEvent is now cancelled, instead of the damage just being set to 0.
@steve4744 could this be confirmed?

**Comment by URoulon** [comment]
It seems like that did the trick. @horgeon backported the change to our custom 5.x build and it works just fine now.
We will be updating to 6.x soon anyway.
