### ISSUE TITLE
Possibility to define a fallheight per course to teleport players to last checkpoint / initial spawn of course.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#22]
Would it be possible to define a fall height to teleport players back to the starting point of the course? i.e. if a player falls more than 3 blocks in height in a specific course, teleport them back to the start. That way I don't have to outline the course in death blocks at the bottom or have it above void.

**Comment by A5H73Y** [comment]
This is already available, in the config.yml find "OnCourse.MaxFallTicks", change this to a lower value to find out what your preferred value should be.

**Comment by mibby** [comment]
Could it be defined per course in case some parkour areas have long fall heights to the next block? Or alternatively, allow defining fall zonez?

**Comment by SpecifiedNull** [comment]
Having option to set MaxFallTicks per course would be very beneficial. we also have some maps that player needs to fall down for about 200 blocks down to a slimeblock. its very fun having to fine adjust falling on 1 single slimeblock and there are many instances on that course like that. so I set MaxFallTicks to 200 in the settings. however this is a bit too much for normal parkour courses, player needs to fall for very long time to respawn to last checkpoint.

**Comment by A5H73Y** [comment]
Wow, 5 years ago.
This has been implemented in the pending 7.0.0 release.
Per-course setting of MaxFallTicks, also being able to set it to 0 to disable it.
Also able to set fall-damage to false to cater for dropper style courses.
