### ISSUE TITLE
Possibility of an autojoin block location.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#23]
Would it be possible to allow defining an autojoin block location? So if a player walks over a certain block or pressure plate (example) in a specific coordinate location, it automatically puts them in a specific course? That way they don't have to right click a parkour sign or type the join command to start a course.

**Comment by A5H73Y** [comment]
This could be considered for a future update.
I know some servers have setup automated systems using other plugins / command blocks to achieve this result.

**Comment by A5H73Y** [comment]
Done in Parkour v5.0 as "/pa setautostart (course)"
