### ISSUE TITLE
Missing placeholder

### ISSUE THREAD

**Issue by LogGits** [A5H73Y/Parkour#248]
I mentioned this on the discord but i think it's better for tracking to have it located here. Placeholder `%parkour_personal_best_{course}%` has not been implemented with the placeholder update. This placeholder is used to gather a players personal best time on a course. If this is implemented could it be implemented with a personal best death placeholder aswell.

in new placeholder format:
```yaml
%parkour_player_personal_best_time_(course)%
%parkour_player_personal_best_deaths_(course)%
```

**Comment by steve4744** [comment]
This has already been implemented in commit 1f84545
