### ISSUE TITLE
Leaderboard with heads

### ISSUE THREAD

**Issue by dadkop** [A5H73Y/Parkour#249]
Hey!

Not a issue but some suggestion. I would like to see if there's possibility to set leaderboard not in chat but into signs and above the signs will create a head with that player. For example I set sign with top 1 player, that will choose that player and above the sign will appear his head. For second place same thing etc.

**Comment by steve4744** [comment]
Hey, there is a plugin that does exactly that:
https://www.spigotmc.org/resources/parkour-top-ten.46268/

**Comment by dadkop** [comment]
Oh, thanks! Then closing this. Sorry
