### ISSUE TITLE
Possibility of setting custom trail per course and sound effects on death/checkpoint/completion.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#25]

**Comment by A5H73Y** [comment]
In later versions of Parkour, I will be adding a store in which you can spend your Parkoins; Allowing you to purchase trails you can equip depending on what you can afford / what you like. I will be adding customisable sounds for more events, but these won't be per course as that's a bit excessive and will consume unnecessary resource.

**Comment by A5H73Y** [comment]
Customisable sounds have been achieved as part of #114. Parkour Trails have been removed, but could be readded using the API with another plugin. Closing issue.
