### ISSUE TITLE
People not playing parkour are going to get teleported to the parkour lobby

### ISSUE THREAD

**Issue by steve4744** [A5H73Y/Parkour#251]
Issue with PlayerListener following #250 - this will teleport non-parkour players who fall into the void to a parkour lobby
```
} else if (!playing && parkour.getConfig().isVoidDetection()) {
                parkour.getServer().getScheduler().runTaskLater(parkour, () -> {
                    parkour.getLobbyManager().teleportToNearestLobby(player);
                }, 1L);
```

**Comment by A5H73Y** [comment]
That's the desired functionality; I agree it's strange as it's unlike anything Parkour has done before. 
I think it's acceptable as some servers may have a floating lobby where players can be handled if they fall off, and most importantly it's disabled by default so will only be enabled by servers with an appropriate set up.
