### ISSUE TITLE
[Bug] Hiding players doesn't work after they reset the course, go back to a checkpoint or join a map.

### ISSUE THREAD

**Issue by janilowski** [A5H73Y/Parkour#255]
Good morning,
I found out that the option to "hide all players" isn't working as intended. When players use it, the item doesn't change to _HideAllEnabled_. Also, when a player who should be invisible restarts the course, teleports back to a checkpoint or joins a course - they become visible too.

Steps to replicate (2 players required):
1. Both players join the same course
2. `Player #1` uses SHIFT + RIGHT-CLICK on the "Toggle visibility" item (`Player #2` should become invisible)
3. `Player #2` restarts the course, teleports back to a checkpoint or rejoins the course
4. `Player #2` is visible to `Player #1` even though they shouldn't be

I've demonstrated the issue in this video: https://youtu.be/vRLLdjPGqdU

I'm using Parkour version 6.2 (newest available on spigotmc.org as of 06.01.2021).
Here is my config: https://pastebin.com/nw8NfQDh
I'm running my server on Paper 1.16.4 (build #391) but the issue is also present on Spigot 1.16.4 #685
My plugin list: 
<img width="243" alt="Screenshot 2021-01-06 at 12 05 40 PM" src="https://user-images.githubusercontent.com/76809077/103761779-832a7600-5017-11eb-8a44-5289a100b0af.png">

**Comment by A5H73Y** [comment]
Thank you for raising this issue, it has now been fixed in the 6.3 release.
