### ISSUE TITLE
Allow parkour tools to be normally right clicked on instead of shift + right click.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#26]
Would it be possible to allow for the parkour tools to just be right click activated instead of requiring shift + right click? Few complaints from some players that it is annoying having to hold shift.

**Comment by A5H73Y** [comment]
Yeah, good idea. I will add in next update, thanks.

**Comment by mibby** [comment]
@A5H73Y You might need to update the tool names if shift interaction is disabled. As the name of the tools  state to use shift.

**Comment by A5H73Y** [comment]
Ah yes I forgot to say this, you'll have to update it manually.

**Comment by mibby** [comment]
That's fine. Wouldn't it be better to have a set of names that are used if the setting is toggled off though for players who don't want to shift + click so they don't have to manually rename themselves?
