### ISSUE TITLE
[Bug] Going back to the last checkpoint in potion mode removes the potion effect

### ISSUE THREAD

**Issue by janilowski** [A5H73Y/Parkour#260]
Good morning,
I found out that when playing on a course in "potion mode" (in my case it's night vision) the plugin removes the potion effect when teleporting back to the last checkpoint. However, when resetting the run, the potion effect is still there.

Steps to replicate:

1. Join a course in "Potion Mode"
2. Shift+right click the item used to go back to the last checkpoint
3. Any potion effects are gone.

I've demonstrated the issue in this video (the course is set to run with NIGHT_VISION): https://youtu.be/m9p7gEjnW-I

I'm using Parkour version 6.2 (newest available on spigotmc.org as of 19.01.2021).
Here is my config: https://pastebin.com/6c52A4HD
Here is my courses.yml: https://pastebin.com/D8Bw7jv2
I'm running my server on Paper 1.16.5 (build #434).
My plugin list:
<img width="360" alt="Screenshot 2021-01-19 at 2 02 28 PM" src="https://user-images.githubusercontent.com/76809077/105037918-fb088f80-5a5e-11eb-9820-1c54ed562df2.png">

**Comment by A5H73Y** [comment]
Hi, thank you for such a well documented issue report.

Fortunately this has already been fixed in a recent commit (https://github.com/A5H73Y/Parkour/commit/3dc389b49889a2c20edc69b6159112634f2a59b8) and is pending a release as Parkour v6.3.
