### ISSUE TITLE
[Bug] Action bar timer does not appear when a player relogs

### ISSUE THREAD

**Issue by janilowski** [A5H73Y/Parkour#261]
Good morning,
I found out that when a player is on a parkour course (with action bar live timer on) and they disconnect from the server and then reconnect their timer is not visible until they restart the course.

To replicate this issue you must have the following config settings:

```
 OnLeaveServer:
  LeaveCourse: false
```
and
```
OnCourse:
  DisplayLiveTime: true
```

Steps to replicate:

1. Join a parkour course with at least one checkpoint
2. Get to a checkpoint and disconnect from the server
3. Rejoin the server
4. The action bar timer is missing

I've demonstrated the issue in this video (look at the action bar): https://youtu.be/drZZYRqDEvk

I'm using Parkour version 6.2 (newest available on spigotmc.org as of 19.01.2021).
Here is my config: https://pastebin.com/6c52A4HD
I'm running my server on Paper 1.16.5 (build #434).
My plugin list:
<img width="217" alt="Screenshot 2021-01-19 at 2 27 06 PM" src="https://user-images.githubusercontent.com/76809077/105040679-6e5fd080-5a62-11eb-92e9-ca1b747c7344.png">

**Comment by A5H73Y** [comment]
Thank you for raising this issue, it has now been fixed in the 6.3 release.
