### ISSUE TITLE
Course Display Names

### ISSUE THREAD

**Issue by A5H73Y** [A5H73Y/Parkour#263]
Having the ability to give the Course a display name will improve the presentation of messages when the Course name is included in the message. For example when you join a Course it may benefit to allow for different cases or colours, instead of it all being lowercase.
There will need to be a distinction of when to use a display name, and when to use the unique name which will identify it within the config. 
The display name will default to the Course identifying name when not specified.

**Comment by janilowski** [comment]
I think it would also be a good idea to display the course creator's nick when a someone joins their course.

Currently it just says "Joined <course>". Maybe there should be a subtitle saying "Created by <nick>"?

**Comment by A5H73Y** [comment]
This has been implemented in 6.7 and improved upon in the pending 7.0.0 release.
