### ISSUE TITLE
Timer resets with "Free Checkpoint" mode and "ResetTimeWithNoCheckpoint" even though the player has a checkpoint.

### ISSUE THREAD

**Issue by janilowski** [A5H73Y/Parkour#265]
Good morning,
To replicate this issue you must have the following config setting:

```
OnDie:
  ResetTimeWithNoCheckpoint: true
```

I understand this setting as "resetting the timer when the player didn't reach any checkpoints". However, on my courses in "Free Checkpoint" mode the timer is reset every time the player dies.

Steps to replicate:
1. Join a course in "Free Checkpoint" mode
2. Get to a checkpoint
3. Die
4. The timer is reset

I've demonstrated the issue in this video: https://youtu.be/IByPGQZZqNg

I'm using Parkour version 6.3.
Here is my config: https://pastebin.com/RZAjUWBx
I'm running my server on Paper 1.16.5 (build 444)
My plugin list:
<img width="507" alt="Screenshot 2021-01-25 at 1 57 21 PM" src="https://user-images.githubusercontent.com/76809077/105708856-461a1b00-5f15-11eb-83a7-f27d8bf3e427.png">

(also, it would be nice to have a sound effect and title for checkpoints in "free checkpoint" mode ;p)

**Comment by A5H73Y** [comment]
Good spot! 
Yeah I'm happy to fix this, and also include the extra details for the free checkpoint GameMode. Thanks again!

**Comment by A5H73Y** [comment]
Fixed, will be included as part of the Parkour v6.4 release.
