### ISSUE TITLE
Incorrect finish time for players who are disconnected by server restart

### ISSUE THREAD

**Issue by osc1997** [A5H73Y/Parkour#266]
## Bug Description
If the server restarts while a player is doing a course, upon re-joining & continuing the course, their time will appear to continue from where they left off, although once they complete the course, their finish time is shorter than expected, it instead is only their time from after re-joining the server.
(Players who disconnect before the server kicks them in order to restart are unaffected)

### Steps to Reproduce:
1. Join a parkour course and get close to the finish.
2. Restart the server while you're still online.
3. Re-join the server and complete the course. (Your finish time should be wrong)

## Plugin & Server Information:
* Plugin Version: 6.3
* Server Version: 1.8.8 (PaperSpigot - "4c7641d")
* Java Version: Version 8 Update 281 (build 1.8.0_281-b09)

## Logs
N/A

**Comment by A5H73Y** [comment]
Fixed in latest commit, will be included as part of the Parkour v6.4 release.
