### ISSUE TITLE
If you reload parkour while players are still in it, they lose their inventory.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#27]
* Joined parkour course.
* Reloaded via /parkour reload
* Left parkour course.
* Inventory was wiped.

Is it not writing the inventory to the inventory.yml?

**Comment by A5H73Y** [comment]
Thank you for the report, I will look into this to see if I can recreate and fix in next version. Thank you.

**Comment by A5H73Y** [comment]
Can't believe this hasn't been found sooner, for some reason I forgot to physically save their inventory. 
This has been resolved in Parkour 4.1.
