### ISSUE TITLE
DiscordSRV Integration

### ISSUE THREAD

**Issue by A5H73Y** [A5H73Y/Parkour#278]
Integrate with the DiscordSRV plugin to allow Parkour to communicate with Discord for certain events. Such as:

- Finishing a Course
- Earning the best time on a Course
- Earning a new ParkourLevel / Rank

Each of these should be disableable, as to not spam server with unwanted information.
A nice solution might be to listen to the Parkour events then send the output straight to the DiscordSRV plugin.

**Comment by Nagol12344** [comment]
You can try using the /discord broadcast command

**Comment by SpecifiedNull** [comment]
Yes, you can use /discord broadcast command however that is very limited to what we can do about the formatting. many plugins already implemented DiscordSVR integration and all we have to do is specify which channel ID it needs to broadcast. and the plugin will broadcast the configured things to the discord automatically given that DiscordSVR and the bot has been properly set up.

So in the configuration we can specify which announcements to be broadcasted on Discord.
For example in parkour config.yml a new section can be added in future updates like the following example:

  # If DiscordBotAPI (https://www.spigotmc.org/resources/discordbotapi.86518/) or DiscordSRV
  # (https://www.spigotmc.org/resources/discordsrv.18494/)is installed, and enabled here.
  # To get Channel-IDs, you must have developer mode enabled in discord. Then, you will right click the channel
  # you want to send a defined message. Then you will click "Copy ID" and paste your clipboard in "Channel-ID"
Discord:
   Enabled: true
    # Specify which channel certain announcement messages get sent.
    Channels:
      PlayerJoinCourse:
        Enabled: true
        Channel-ID: 821043826504237148
      PlayerReachCheckpoint:
        Enabled: true
        Channel-ID: 821043826504237148
      PlayerFinishCourse:
        Enabled: true
        Channel-ID: 821043826504237148
      BestTimeEver:
        Enabled: true
        Channel-ID: 821043826504237148
      BestTimeEver:
        Enabled: true
        Channel-ID: 821043826504237148
      PlayerRecievedReward:
        Enabled: true
        Channel-ID: 821043826504237148

**Comment by A5H73Y** [comment]
I'm afraid I'm not going to continue with this task, I don't want to add another plugin dependency to the project.
As most discord functionality can be achieved through commands, paired with Parkour's event system and placeholders this should be achievable without the linking of the two.
