### ISSUE TITLE
Fly mode does not turn off if you enter parkour mode while flying in the air.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#28]
Compiled as of https://github.com/A5H73Y/Parkour/commit/7dea8ea280a20f32f7850c3c07c66ee32662dca1

Apparently flymode does not turn off when entering parkour mode while you are flying in the air prior to joining. It only disables fly if you are on the floor and had it turned on.

**Comment by A5H73Y** [comment]
Fixed in next commit.

**Comment by mibby** [comment]
Seems to be working great now, thanks.
