### ISSUE TITLE
Could not pass event PlayerMoveEvent to Parkour v6.5 | 1.16.5

### ISSUE THREAD

**Issue by Thrashjoking** [A5H73Y/Parkour#283]
Hello, the following spam appears on the console:
[15:36:00] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Parkour v6.5
java.lang.NullPointerException: null
My server version is 1.16.5 with Java 15.

**Comment by steve4744** [comment]
Thanks for the report. Can you attach the full console log please.

**Comment by Thrashjoking** [comment]
https://pastebin.com/jMJa5tLd

**Comment by steve4744** [comment]
Looks like you could have an invalid or non-existent kit assigned to a course. Check your courses.yml file for linked kits that don't exist.

**Comment by A5H73Y** [comment]
Fixed in v6.6 release.
