### ISSUE TITLE
Players dont get any reward, then "RewardOnce: true" option is set.  

### ISSUE THREAD

**Issue by Sandukhan** [A5H73Y/Parkour#286]
Hello,
i had some issues with parkour, running on:

- Parkour 6.5
- paper 1.16.5 (Build 651)

First of all, the option "RewardOnce: true" disables any kind of reward, even for players who never played the course before.
Otherwise the system seems to work fine with repetitive rewards active (a.k  "RewardOnce: false")  

 Course settings:

 https://pastebin.com/Zj8k6d77
  
  Also deleting player session data dosent seem to work:
  
  https://pastebin.com/JUbXhQ6n
  
  And a nullpointer with tab complete:
  
  https://pastebin.com/dMHuWf1q

**Comment by A5H73Y** [comment]
Fixed in v6.6 release.
