### ISSUE TITLE
Maven repository not accessible

### ISSUE THREAD

**Issue by mindw0rm** [A5H73Y/Parkour#289]
The maven repository given in the readme (https://github.com/A5H73Y/Parkour#maven) cannot be accessed, all paths return 403 forbidden.

**Comment by A5H73Y** [comment]
Thanks for raising this, bintray is now closing down and I planned to migrate to Github releases.
I'll make progress more urgent, thanks.

**Comment by A5H73Y** [comment]
Changed to use jitpack. AAC and BountifulAPI support has been dropped due to issues with their repos, but I'm not too upset.
