### ISSUE TITLE
Pkr and Parkour not registered as parkour commands.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#29]
Compiled as of https://github.com/A5H73Y/Parkour/commit/7dea8ea280a20f32f7850c3c07c66ee32662dca1

```
  EnforceParkourCommands:
    Enabled: true
```

Players inside parkour mode can't use /parkour or /pkr commands to leave. Is it only registering /pa as parkour commands? I removed the /pa alias since I have another plugin that uses /pa for PVP arenas.

**Comment by steve4744** [comment]
"/parkour leave" works fine for me, as does the GUI item to leave the course.

You could always add pkr as a whistlisted command:
"/pa whitelist pkr".

/pkr can then be used in-game.

**Comment by A5H73Y** [comment]
@mibby Please validate what @steve4744 has suggested, before I raise this problem, thanks both.

**Comment by mibby** [comment]
My apologies. It seems /parkour does work but /pkr is not registered as a parkour command. I get the ```Non-Parkour commands have been disabled!``` output in chat when trying to type /pkr leave.

**Comment by steve4744** [comment]
The pkr alias is defined in the plugin.yml with pa - as you removed pa, did you leave the pkr alias definition?

As a test you could try the original parkour and plugin.yml to see if /pkr works. As I said it works for me in-game.

**Comment by mibby** [comment]
Yes, I left the pkr alias definition in the plugin.yml.

Are you opped / grouped admin who inherits bypass permissions and certain you don't have /pkr in the whitelist list? As me testing without any inherited parkour permissions, wildcards, or OP bypasses, was not able to use /pkr.

**Comment by A5H73Y** [comment]
You are correct in that pkr was not considered a Parkour command, I've fixed in next commit.
However @steve4744  suggested that you whitelisted the command, which would have fixed the problem.

**Comment by mibby** [comment]
Whitelisting would have indeed solved the problem, but being that it is a registered alias, just thought it should be allowed by default, especially for people who are unaware and wouldn't have added it to the whitelist. 

Being that it is now set in the latest commit, I will close this ticket. :)
