### ISSUE TITLE
Trying to use a non-placeable material as Freedom ParkourTool causes the save-load mechanism to not work

### ISSUE THREAD

**Issue by URoulon** [A5H73Y/Parkour#302]
The title says it all. We're running 6.7.1 on a Paper 1.16.5 server.

We're trying to replace the Redstone Torch by the Totem of Undying as the ParkourTool for the Freedom mode
but it doesn't work like the other ParkourTools (the stick is non-placeable but still works as the default Exit item).

**Comment by steve4744** [comment]
This issue should now be fixed in 7.0.

**Comment by URoulon** [comment]
Closing the issue, it is fixed indeed.
