### ISSUE TITLE
Not able to change /pa language in help commands.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#31]
I disable the /pa alias in the plugin.yml since I have another plugin (PVPArena) that uses the /pa command. Would it be possible to allow for changing the language in the parkour help menus?  For example, ```/pkr cmds``` and ```/pkr cmds 1``` output everything as ```/pa``` instead of ```/parkour``` or ```/pkr```. The strings.yml does not have language strings for the help menus.

**Comment by A5H73Y** [comment]
All references to Parkour command syntax is now configurable in the strings.yml file.
