### ISSUE TITLE
%AMOUNT% has an extra space in the output.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#32]
i.e.

```
  Reward: You earned &b%AMOUNT% &ffor completing &b%COURSE%&f!
```

The actual in-game output has two spaces after the amount displayed. So instead of just replacing %amount% with a number, it is adding an extra space after the number in addition to it - resulting in two spaces in that language example.

**Comment by A5H73Y** [comment]
I'm assuming this is in regards to the Economy Reward, this is because the currency name is blank or null then. I will fix this in next update.
