### ISSUE TITLE
Restarting the course doesn't update XPbar death-tracker.

### ISSUE THREAD

**Issue by Kassespar** [A5H73Y/Parkour#320]
When using the Restart Course item, your current amounts of deaths resets, as it should. But the XP-bar Death tracker does NOT reset. 
The XP-Bar death tracker only updates once you use the Last Checkpoint item.

Attached files:
#1: 8 deaths
![2022-03-20_19 28 13](https://user-images.githubusercontent.com/24629435/159177139-de39c31f-3984-4680-a73e-02a64d027ccb.png)

#2 Uses reset course item, Still 8 deaths
![2022-03-20_19 28 17](https://user-images.githubusercontent.com/24629435/159177155-d8208280-2a14-4430-b96f-b1222d4668bf.png)

#3 Uses Last Checkpoint item in start area, updates to 1 as you technically die so you go from 0 to 1.
![2022-03-20_19 28 21](https://user-images.githubusercontent.com/24629435/159177194-e99a42a3-3e1d-4dfa-a19d-aabff98c043b.png)

**Comment by A5H73Y** [comment]
Thank you for raising this issue.
This has been fixed in the pending 7.0.0 release.
