### ISSUE TITLE
Placholder ERROR

### ISSUE THREAD

**Issue by archroot** [A5H73Y/Parkour#325]
![image](https://user-images.githubusercontent.com/41123605/175275467-89db6246-cbca-44ce-bdf6-f5d62d72cfdb.png)

**Comment by A5H73Y** [comment]
Hi, ParkourExpansion is no longer required and the functionality is included in the Parkour plugin itself.
More information here: https://a5h73y.github.io/Parkour/#/guides/compatible-plugins?id=placeholderapi
