### ISSUE TITLE
[Bug] Item toolbar got reset after course reset

### ISSUE THREAD

**Issue by Whitebrim** [A5H73Y/Parkour#335]
I use different items for `hide players` and `show players`, it works fine, but if player hides other players (item changes to `show players`), then player use `reset course` item, `show players` item got reset to `hide players`.

After player use item to hide other players, item is changed to gray dye:
![image](https://user-images.githubusercontent.com/23287829/201483709-984f9b90-a30c-433c-822a-9c14200d8f5e.png)
Then after player reset course, item that should remain gray dye because lime dye (`hide players` item):
![image](https://user-images.githubusercontent.com/23287829/201483715-5570017e-365d-4dc8-b365-96189c16eb39.png)

Expected behavour:
After player reset course with `reset course` item, activated `hide players` will stay the same and not got visually changed to default state.

**Comment by A5H73Y** [comment]
This should be fixed with the latest release.
