### ISSUE TITLE
Support for data values in material name.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#36]
Would it be possible to support data values in material names for block sets? So you can use specific type of dirt or a specific color of wool.

I.e.

```
  Finish:
    Material: WOOL:15
```

**Comment by A5H73Y** [comment]
Nope, Bukkit has completely depreciated data values as they're just magic numbers.
When there is a safe way of doing it, I will implement it.

**Comment by mibby** [comment]
Then how would one choose a specific wool color? They don't go by the material name of ORANGE_WOOL.
