### ISSUE TITLE
Option to blacklist commands while in parkour mode.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#39]
Would it be possible to implement a way to blacklist commands not allowed while in parkour mode? For example, I'd like to block the command ```/pa``` while players are in parkour because the arena plugin I use (PVPArena) uses that command alias to join arenas.

Despite ```pa``` being removed from the plugin.yml as a registered parkour command alias, because it is allowed in the source as a parkour command here https://github.com/A5H73Y/Parkour/commit/d3cbb66f46a7bfcc1755b11293a3769b999f9f7d#diff-eb8d94763a93fd55979b0adb3e6bc5eaR394,  players are able to join the arenas from within parkour with invincibility.

**Comment by salasan1** [comment]
I recommend use PerWorldPlugins. You can get it in here
https ://www.spigotmc.org/resources/perworldplugins.32751/

**Comment by A5H73Y** [comment]
The condition is now based on command aliases, if the entry is removed from the plugin.yml it will also be blocked whilst on a Course.
