### ISSUE TITLE
Able to walk away from the parkour course and use the parkour tool materials to craft items.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#44]
Compiled as of https://github.com/A5H73Y/Parkour/commit/d3cbb66f46a7bfcc1755b11293a3769b999f9f7d

People can enter parkour mode and then just walk to their house or somewhere in the world that isn't protected if the parkour course is open, such as if in an open course around spawn. Then they could have setup a chest with items in it and use a workbench to craft items with the parkour tools. In my case, using glass and obsidian from a chest and crafting a beacon with my nether star parkour mode item.

1) Would it be possible to set a range limit for how far someone is able to walk away from that parkour course's lounge before being teleported back? Or alternatively defining a parkour cuboid region for the course that they aren't allowed to leave.

2) Would it be possible to block all interaction with the parkour items to avoid dropping / crafting? They would not need to be able to interact with chests, enderchests, or really any kind of inventory GUI such as a furnace, workbench, etc.

**Comment by A5H73Y** [comment]
The first suggestion will not be implemented using the Parkour plugin, it's not in my interest to create something like that.. using a plugin similar to WorldGuard I'm sure you could get the desired result.
The second suggestion will be addressed, but in an ideal world you wouldn't place crafting benches etc. on a Parkour course for the player to use.

**Comment by steve4744** [comment]
You can prevent items being dropped by setting "OnCourse:DisableItemDrop: true" in the config.

You could also make use of the 'death block' to prevent players moving away from the course.

**Comment by A5H73Y** [comment]
Hi @mibby,
To address all issues that could arise, I've given the option to force the prevention of block place / breaking, even for ops. As well as an option to prevent all inventory opening, besides the players inventory (which could also be blocked).
Hope this would resolve the problem.
