### ISSUE TITLE
Toggling player visibility breaks players who were invisible prior outside of parkour.

### ISSUE THREAD

**Issue by mibby** [A5H73Y/Parkour#46]
Compiled as of https://github.com/A5H73Y/Parkour/commit/d3cbb66f46a7bfcc1755b11293a3769b999f9f7d

Players who toggle player visibility are able to see those who were invisible prior to joining, such as staff members who went invisible to watch over another player.

* Player1 (staff) /vanishes.
* Player2 joins parkour.
* Player2 toggle hides all players, then toggle shows all players.
* Player2 leaves parkour.
* Player2 is now able to see Player1 who was originally vanished.

In my case, I use VanishNoPacket (https://dev.bukkit.org/projects/vanish) in conjunction with ProtocolLib to force certain players vanished and for staff members to hide from others. It to my knowledge hides players by removing the player packet directly so hack clients can't see sent nearby player packets. When someone toggles hidden players within parkour, it allows vanished players to be shown to that player. Thus;

1) Would it be possible to respect current invisible / vanished players not handled by Parkour to not refresh / display them when someone toggles all players visible when they shouldn't have access to seeing those players?

2) Would it be possible for Parkour to only toggle players invisible / visible who are actually part of parkour mode / of that parkour course instead of everyone globally?

**Comment by A5H73Y** [comment]
I've gone for option 2 as it makes the most sense without over complicating things.
Will test then commit.

**Comment by mibby** [comment]
@A5H73Y This doesn't seem to be working. 
```
    HideAll:
      Material: BONE
      Global: false
```

Toggling the bone with two people in the same course, players don't vanish (or reappear, but can't test that since they don't vanish to begin with on toggle). Also noticed you can't spam click the tool a second after using it, slight cooldown on it?

**Comment by A5H73Y** [comment]
That is bizarre, I tested with 1 other player and it seemed to work, so I will look into it.
Yes I added a 1 second cool down, just in case.

**Comment by mibby** [comment]
@A5H73Y Bump. A fix would be nice as soon as possible. :( Lots of reports of it not working (toggling players hidden who are part of the same parkour course / in parkour mode) when global is set to false.

**Comment by A5H73Y** [comment]
Wait, have we misunderstood each other? By the way your describing, it sounds like it's working.
If global is on, it will hide / show ALL players on the server
If global is off, it will hide / show players who are in Parkour mode..?

**Comment by mibby** [comment]
That would be ideal behavior, however it isn't hiding any players who are in parkour mode whatsoever.

**Comment by A5H73Y** [comment]
@steve4744 are you able to recreate this? I'm not. :/

**Comment by steve4744** [comment]
Ok, I've got global set to false. With both players playing on the same course:
If I click the bone, the other player goes invisible (although she can still see me). Click again she is visible again. The reverse is also if she uses the bone.

If we both click the bone, then we are both invisble at the same time.

So I dont have a problem with it - seems to work as I would expect.

**Comment by mibby** [comment]
@A5H73Y Sorry, been busy. Here is a video reproducing the problem. Tested and compiled Parkour as of commit https://github.com/A5H73Y/Parkour/commit/90aec0c7a8c4833392649f209b3fdec47d761454 (4.1 release build).

https://www.dropbox.com/s/fgs60edb7a3cxgf/2017-06-01%2004-12-37.mkv?dl=0

* With global disabled, showed that players not part of parkour do not toggle (Good)
* Showed players both part of the same parkour course do not toggle (Bad)
* Re-enabled global and reloaded parkour from console, showed global toggles all players (Good, but not intended behavior I'd like - I would like it so only players part of parkour can toggle others inside parkour rather than everyone globally)

**Comment by mibby** [comment]
I tested by removing every plugin one at a time. The conflict seems to be with EssentialsXChat for whatever reason.

I use EssentialsX dev 473. All EssentialsX jars work fine with the exception of the chat one installed. Perhaps the way you are looking for players by name causes it to break?

https://github.com/drtshock/Essentials
https://ci.drtshock.net/job/EssentialsX/

**Comment by steve4744** [comment]
Does this help?
https://github.com/drtshock/Essentials/issues/145

**Comment by mibby** [comment]
Not sure how that is related. I don't have an issue with people randomly vanishing, just Parkour can't toggle vanish players in a parkour course with global disabled when Essentials Chat is installed.

**Comment by steve4744** [comment]
True - its a different issue but there appears to be a conflict between EssentialsX and VnP according to the last couple of posts. The workaround for him was to remove the vanish part from the plugin.yml of EssentialsX.  Just thought it might be worth trying.

**Comment by mibby** [comment]
The conflict issue has nothing to do with VanishNoPacket and Essentials though. It breaks outright with just EssentialsChat installed presumably because of the way names are looked up in Parkour.

**Comment by A5H73Y** [comment]
Yes, you could be correct. If another plugin somehow changes their name to what Parkour expects then things go wrong, I test my plugin on a vanilla server so I am usually confident that problems are caused by 3rd party plugins.
Looking at https://github.com/A5H73Y/Parkour/blob/master/src/main/java/me/A5H73Y/Parkour/Utilities/Utils.java#L875-L885
Could you debug to see if the names differ and are not matching, thus making the plugin think they're not playing Parkour? @mibby @steve4744 
Hope this helps.

**Comment by mibby** [comment]
@A5H73Y 
> Could you debug to see if the names differ and are not matching, thus making the plugin think they're not playing Parkour?

How would I go about testing that? Can you provide me a debug build that outputs the name of all players attempting to toggle when using the tool?

**Comment by mibby** [comment]
@A5H73Y Any update? :(

**Comment by A5H73Y** [comment]
Very quickly created a (hopeful) fix version for you, because I'm working on upgrading the dev build website at the moment.
https://www.dropbox.com/s/p0xo8m9hh8bu05l/Parkour.jar?dl=0

**Comment by A5H73Y** [comment]
@mibby did it work?

**Comment by mibby** [comment]
@A5H73Y Sorry, busy week for me. That version does seem to fix the problem. However if you toggle players who are part of that course invisible and they leave the arena, they stay invisible for that player. You can't toggle them visible again with the tool since it is arena specific - not global. You'll need to make it so visibility is forced re-enabled when a player leaves the parkour course if invisible.

**Comment by A5H73Y** [comment]
I thought I understood the problem, but we're going in circles. There's no way I'm going to know who has done '/vanish' and to keep them hidden once HideAll is disabled. This simply isn't possible without hooking into the 3rd party plugin and somehow getting the vanished players and exempting them. (Which I won't be doing). 
I will add the override so that once you leave / finish a course, all players will be visible again, but this just contradicts your original request.

**Comment by mibby** [comment]
Perhaps you are resetting all vanished players when _you_ as a player leave the parkour course but not when those who are toggled invisible _to_ you leave?

**Comment by mibby** [comment]
Bump. ^^

**Comment by mibby** [comment]
Bump.

**Comment by A5H73Y** [comment]
Hey mibby, it's hard to diagnose the problem when I don't understand what it is.
If you could add me either on skype: **iA5H73Y** or join the ParkourSupport Discord server: [**Click here**](https://discord.gg/aENfFKK)

**Comment by mibby** [comment]
@A5H73Y I'm receiving reports that this is apparently still broken. With local toggling, players are able to toggle vanished people, i.e. staff not part of the course, visible.
