### ISSUE TITLE
Ability to make a mutli selection a checkpoint

### ISSUE THREAD

**Issue by yannick1691** [A5H73Y/Parkour#50]
The one thing im missing in this plugin is the ability to make a checkpoint out of for example a worldedit selection. 

So for example instead of a pressure plate. I would select 1 bottom corner and 1 top corner of a area, and i could make a checkpoint if a player enters that area. Instead of when they step on a pressure plate. 

This would be very usefull when you are making a map where for example players walk through a cave and you want them to get a checkpoint when enterering a part of the cave. 
Because a cave is a bigger area and with different block height. The changes of a player missing a pressure plate here are quite high. 

I would like to request if you could consider adding this feature to your plugin.

**Comment by A5H73Y** [comment]
Thank you for the suggestion and I agree this would be very helpful for many courses. 

Unfortunately given the performance hit and the dependencies on WorldEdit / WorldGuard (for checking areas), it just isn't practical given the design of the plugin.
This would be achievable using a 3rd party plugin as there is functionality accessible using the plugin, but I will not be doing such a task. With that said, if you wish to take on the task (or find someone that will), and I approve the implementation, I will happily incorporate it into the plugin.

Kind regards.

**Comment by Ghostlyr** [comment]
@A5H73Y, could you implemet simple possibility for assigning one checkpoint ID to several blocks?
