### ISSUE TITLE
[Request] PlaceholderAPI and/or an API

### ISSUE THREAD

**Issue by cwkfr** [A5H73Y/Parkour#56]
Thank you ;D

Edit: oh well, I just browse thru the source. My bad :(

**Comment by A5H73Y** [comment]
I've started to create a PlaceholderAPI:
[ParkourPlaceholders.java](https://github.com/A5H73Y/Parkour/blob/master/src/main/java/me/A5H73Y/Parkour/ParkourPlaceholders.java)
I will include more features soon, I'm very busy at the moment.
