### ISSUE TITLE
Maven uses src/plugin.yml instead of plugin.yml

### ISSUE THREAD

**Issue by horgeon** [A5H73Y/Parkour#57]
It's not really an important problem, but when PlaceholderAPI support will be complete, it may induce some bugs, since it will consider the wrong plugin.yml file.

**Comment by A5H73Y** [comment]
@steve4744 Any idea?

**Comment by steve4744** [comment]
No, sorry. I don't see why PlaceholderAPI will cause an issue if pom.xml is set up correctly?

**Comment by horgeon** [comment]
It's just that's it's that Maven is (supposedly) including the wrong plugin.yml file. It shouldn't cause problems.

**Comment by A5H73Y** [comment]
I've fixed this in latest commit?
