### ISSUE TITLE
Teleport delay on finish course

### ISSUE THREAD

**Issue by steve4744** [A5H73Y/Parkour#6]
Done a bit of testing on this....the 'delay' itself works fine, the problem is that during the 'delay' the player can/will move across the finish block(s), so the 'onPlayerMove' listener is triggering multiple playerFinish events.  This causes multiple 'player finshed course' messages to appear and the prize (e.g.1 diamond) is  given to the player multiple times.

**Comment by A5H73Y** [comment]
My apologies I didn't test this scenario, quick fix just needed to remove the player from the playing list.
Fixed. Thanks again! :)
