### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KonoromiHimaries** [A5H73Y/Parkour#64]
logs
https://gist.github.com/mat41997/850abf55546dcc6b3506a14017ac68e2

timings
https://timings.aikar.co/?id=2fedfe3aa03d4f62b8cb68d6502b44e1#plugins

**Comment by A5H73Y** [comment]
I haven't got a clue what caused that error, only obvious thing is that you're using 'Torch' which I hadn't even heard of until today. I will attempt to recreate this using that server when I find the time and update the ticket accordingly.

**Comment by A5H73Y** [comment]
Haven't had this raised since, closing issue.
