### ISSUE TITLE
Unhandled exception executing command 'pa'

### ISSUE THREAD

**Issue by Deathinflames** [A5H73Y/Parkour#67]
Hello,

We are currently running Parkour v4.1 using MySQL as our database option and we seem to be receiving an error when executing ` /pa stats map`.

The error happens regardless of what map we try to check the stats for. Here is the stack trace for the error: https://pastebin.com/raw/EgQBmAii

Looking at the source, it seems to be related to the join fee of a course, is that right?

Thank you!

**Comment by steve4744** [comment]
Hi,

You are correct in that its related to the JoinFee. You will get that error if you don't have Vault installed. I will try and add a check for Vault in 4.2, but for now installing Vault will fix the error.

Thanks.

**Comment by Deathinflames** [comment]
That's strange, i do have Vault installed though, Vault v1.5.6-b49 to be exact. I guess it's an issue with older versions of Vault?

**Comment by steve4744** [comment]
Its the same version of vault I have - don't think is been updated in a long time. 
You could check in config.yml that you have
Other:Economy:Enabled: true

**Comment by A5H73Y** [comment]
Assuming problem is resolved now. Parkour 4.2 will contain the fix when released.
