### ISSUE TITLE
TitleActionbarAPI doesn't support Minecraft versions newer than 1.9

### ISSUE THREAD

**Issue by mikroskeem** [A5H73Y/Parkour#7]
Maybe you could consider using other ways to send title to player? For example using /title command or ConnorlinFoot's TitleAPI (1.7-1.11 according to my testing)
TitleAPI can be used via static methods, which fits perfectly here imo

**Comment by steve4744** [comment]
Spigot 1.11 has native support for bossbars:
[https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BossBar.html](url)

I think that is the way to go rather than depending on 3rd party plugins.

**Comment by A5H73Y** [comment]
Thank you both for the contribution, not really sure what to do yet. I would like to support as many versions as possible, so the Spigot 1.11 change would only work for servers using Spigot 1.11 :stuck_out_tongue: 
But I may consider the TitleAPI, but that doesn't include the action bar... If I'm honest I consider writing my own plugin to do it at this stage :laughing:

**Comment by mikroskeem** [comment]
[BountifulAPI](https://www.spigotmc.org/resources/bountifulapi-1-8-1-9-1-10.1394/) includes both Title and Actionbar sending. It is ActionBarAPI + TitleAPI, all of them are made by same author.

**Comment by steve4744** [comment]
@A5H73Y : The spigot change is actually from 1.9 onwards - which is maybe why a lot of the old bossbar api's have not been updated past 1.9.

@mikroskeem : BountifulAPI looks ok but hasn't been updated since June and is still on 1.10, and so not much different from TitleActionBarAPI for me (on 1.11).

Happy Christmas both!

**Comment by mikroskeem** [comment]
@steve4744 BountifulAPI runs fine on 1.11 according to my testing.

**Comment by A5H73Y** [comment]
Thanks again both, I've decided to go with Bountiful and I've made the full conversion and confirms it works with the latest versions as it isn't version specific (unlike TitleActionBar), I'll commit this now. 
Happy Christmas, both!
