### ISSUE TITLE
Suggestion: Prevent players from attacking other entities

### ISSUE THREAD

**Issue by horgeon** [A5H73Y/Parkour#75]
At the moment, the plugin prevents players that are on a course from being attacked.

It would be nice to add an option that also prevent them from attacking and/or killing/destroying others entities, such as animals, armor stands, hangable entities like item frames and paintings.

You can see my solution [here](https://github.com/Prodrivers/Parkour/commit/5b1d5112cecdf1cd7b8128927807583d1facc619)

**Comment by A5H73Y** [comment]
Good suggestion and I wouldn't have ever thought of it.
If you'd like to create a pull request I'd be happy to add it to the plugin, thank you :)

**Comment by horgeon** [comment]
I opened up the pull request, if you have any concern other concerns with it, please tell me.
Note that this does not prevent players from interacting with other entities. I think it can be useful to prevent this as well, but in a separate option. What do you think of it?
