### ISSUE TITLE
How to stop auto update ?

### ISSUE THREAD

**Issue by Lostas** [A5H73Y/Parkour#85]
After the new 4.3 update, all default and not default blocks with effects stopped working. I can't find auto update disabling in the config.

**Comment by A5H73Y** [comment]
Hi Lostas,
Parkour 4.2 brought a new way of doing Parkour Blocks, in the form of a ParkourKit. These are easy to modify and setup and shouldn't take more than a minute to get back to how it was.
Please find https://dev.bukkit.org/projects/parkour/pages/tutorial/part3 to help.
In the config.yml find "Other.CheckForUpdates" and set this to false.
