### ISSUE TITLE
In-game whitelisted commands in config.yml are ignored.

### ISSUE THREAD

**Issue by steve4744** [A5H73Y/Parkour#9]
The config.yml maintains a list of whitelisted commands which can be used in-game if "EnforceParkourCommands" is enabled.

Any commands included in whitelist are ignored due to the code referencing node "Other.Commands.Whitelist" instead of "OnCourse.EnforceParkourCommands.Whitelist" in the config.yml.

**Comment by A5H73Y** [comment]
Hey Steve, thanks again for helping me find bugs.
I have a rather massive update soon to commit so to avoid complication (I'm not great at using git), I will include your fixes and add you in the message as a thanks.
Kind regards,
Ash

**Comment by steve4744** [comment]
Hi Ash,
That's absolutely fine - whatever's easier.  I found this one by accident while testing the perworldinventories plugin.
Thanks,
Steve
