### ISSUE TITLE
Can't remove prize

### ISSUE THREAD

**Issue by HVcraft** [A5H73Y/Parkour#98]
If I set a prize on a Parkour, I cannot delete it. I cant find anything in the files in the plugins folder.

**Comment by A5H73Y** [comment]
Hi HVcraft,
So the course prizes are stored in the courses.yml, and will follow the format: (course).Prize.(type): (value)
For example: 

> level1.Prize.XP: 500
You can manually remove this when the server is stopped, save and start the server again and this will remove the prizes.
If it makes life easier, I can add an option into the "/pa prize (course)" conversation, named "reset" that will remove all the rewards attached to that course?

**Comment by HVcraft** [comment]
Thank you :D I didn't see that. I don't need it with the /pa prize command,
but I think it might be helpful for other people. Thank you for the fast
support! I really like you plugin!

**Comment by A5H73Y** [comment]
Thank you for the feedback.
I have added "/pa reset prize (course)" to make this process easier; closing ticket.
